### ISSUE TITLE
Android Chrome: can't cancel order

### ISSUE THREAD

**Issue by greacen** [labzero/adpq#250] opened 2017-03-03 01:45 UTC
1. Sign in
1. navigate to Account
1. click order id
1. click cancel button
1. boom- nothing happens (no message, no cancellation)

`
u: User10
p: user
`

**Comment by greacen** [comment] 2017-03-03 19:51
I see this working with the current build

**Comment by w1150n** [comment] 2017-03-03 19:52
Closing since we can't reproduce it..

**Closed by w1150n** 2017-03-03 19:52 UTC
Labels: bug
